### ISSUE TITLE
Link to CIViC variant pages in the VCI

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#102]
Link to the CIViC variant page in the VCI (see slide 2): https://docs.google.com/presentation/d/1Oa16A3J-FqerQzwtJy656FwJXaiv0bdN5Z185QwglGc/edit?usp=sharing

* Reconfigure the LOVD table as shown in the mockups
* Add a link to CIViC if available 
* Display a message if no link is available

**Comment by wrightmw** [comment]
Released 10/01/2021
