### ISSUE TITLE
Automatically add VCEP specification to provisional and approved snapshots

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#115]
When a user has selected a VCEP specification version to use in their variant interpretation, then when they go to save a provisional and/or approved interpretation then it should automatically include the name of the VCEP specification version that was used in the provision/approve panel. This version number should be saved in the snapshot, and when published it should be included in the ERepo message.

**Comment by wrightmw** [comment]
@markmandell was this already included in the CSpec release?

**Comment by markmandell** [comment]
> @markmandell was this already included in the CSpec release?

Hey @wrightmw, yes the v1 of CSpec adds the chosen criteria specification (I believe full title w/ version) to the provisional and approval snapshots.

**Comment by wrightmw** [comment]
Thanks @markmandell ... I will close this then
