### ISSUE TITLE
Variant Prioritization (VP) minor updates

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#118]
![Screen Shot 2021-11-11 at 10 31 19 PM](https://user-images.githubusercontent.com/15131169/141421061-b5952a37-601f-46ad-b6b8-34f1d60300fd.png)

![Screen Shot 2021-11-11 at 10 26 03 PM](https://user-images.githubusercontent.com/15131169/141420696-4d86070a-340d-44b5-b201-1b284557b2a0.png)

![Screen Shot 2021-11-11 at 10 26 10 PM](https://user-images.githubusercontent.com/15131169/141420705-e6170521-b8cf-42fb-8243-6c93262656a7.png)

![Screen Shot 2021-11-11 at 10 26 15 PM](https://user-images.githubusercontent.com/15131169/141420721-08f6e64f-e062-4059-86a8-7b69e911ca23.png)

![Screen Shot 2021-11-11 at 10 26 22 PM](https://user-images.githubusercontent.com/15131169/141420740-93d697c1-1e6f-488d-9229-e53210e55d14.png)

**Comment by markmandell** [comment]
merged to prod 1/27/22

**Comment by markmandell** [comment]
merged to dev 1/28/22
