### ISSUE TITLE
Display warning when user is viewing duplicated PMIDs in the case/seg table 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#125]
To enable curators to identify and eliminate double counting in the case/seg tab: 

1. Provide a visual cue the length of the column for PMIDs that are duplicated
2. Display warning symbols and hover-over language when duplicate PMIDs are displayed in the Case/Seg tab 
3. The mockup slides are here, with the relevant slides being "feature 1" (slides 7-11) https://docs.google.com/presentation/d/1Y4oi4lP-72xrDK1AzlAxTWwVlV2XKRPzBrl9rToc7lg/edit#slide=id.g1104afc3cf9_0_86

SP ticket: https://broadinstitute.atlassian.net/browse/CGSP-617

**Comment by cgpreston** [comment]
Potential mockup, to be discussed with the VCI proxy group:
<img width="883" alt="Screen Shot 2022-01-20 at 9 41 24 AM" src="https://user-images.githubusercontent.com/46766411/150392742-fade468d-f6da-42a2-9eb5-366e52c6bc7b.png">

**Comment by liammulh** [comment]
I think as of https://github.com/ClinGen/gci-vci-aws/commit/7871db11673e53faa3936157fb0ffe8d6fdf38e2, feature 1 has been implemented.

**Comment by liammulh** [comment]
This is now in prod, closing.
