### ISSUE TITLE
Add 0.25 increments to variant scoring pulldowns in GDMs

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#151]
When scoring variants in the GCI, currently the options are:
0, 0.1, 0.25, 0.5, 1.0, 1.5, 2, and 3

![Screen Shot 2022-02-14 at 2 04 58 PM](https://user-images.githubusercontent.com/15131169/153954686-4fe8952e-20a5-443f-bdc0-95103d7982dd.png)

These options need to be update to include extra 0.25 increments, so they would instead be:
0, 0.1, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2, 2.25, 2.5. 2.75 and 3

https://broadinstitute.atlassian.net/browse/CGSP-467

**Comment by ErinRiggs** [comment]
That's right!  Is there any reason they shouldn't just be deployed everywhere (e.g., experimental evidence, case control, etc.)?

**Comment by wrightmw** [comment]
@ErinRiggs We could just apply the above values in all scoring pulldown in the GCI, if you'd like that?

**Comment by courtneythaxton** [comment]
@wrightmw I agree with Erin, add this to all scoring pull downs from genetic to experimental.
