### ISSUE TITLE
Missing VCI curation

### ISSUE THREAD

**Issue by msingerb** [ClinGen/gene-and-variant-curation-tools#157]
I was looking through some old curations of ours (Broad Institute Rare Disease Group)  in the VCI and found one that we had made a page for but now seems to be missing. I have the link from the original page but it doesn't work anymore. Can you help us figure out if this was deleted somehow? The link is below:
https://curation.clinicalgenome.org/variant-central/?edit=true&variant=ec84687d-5f24-4245-[…]ation=073032e2-cfef-41e4-8b5e-67d816e69fc0&summary=true](https://curation.clinicalgenome.org/variant-central/?edit=true&variant=ec84687d-5f24-4245-ae3e-83957f5960ea&interpretation=073032e2-cfef-41e4-8b5e-67d816e69fc0&summary=true

**Comment by cgpreston** [comment]
Hi @msingerb, with the December 2020 rearchitecture the URL structures have slightly changed. You should be able to access the variant using the URL https://curation.clinicalgenome.org/variant-central/ec84687d-5f24-4245-ae3e-83957f5960ea/.
