### ISSUE TITLE
Make GCI/VCI affiliations accessible via API

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#160]
Currently, GCI/VCI affiliations data is publicly accessible via a manually maintained spreadsheet. We need to make the affiliation data within our resource publicly available via API so that other ClinGen resources (such as the GeneTracker and GPM) can make use of this information.

https://broadinstitute.atlassian.net/browse/CGSP-451

**Comment by cgpreston** [comment]
Signed off by stakeholders, closing. This was finished and reported as such for the Dec 21 -March 22 cycle.
