### ISSUE TITLE
Assign ownership of each GDM to one GCEP only

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#161]
The GCI was initially envisaged as a community curation tool, similar to the VCI. Later it was decided to restrict the GCI to use by GCEPs only.  An additional layer of complication was that the GCI was designed for multiple groups to make their own parallel classifications on each GDM, but now it is required that only one GCEP at a time should be working on a classification for a given GDM.  As such, the GDMs need to be cleaned up so that each GDM only has one GCEP current owner.

https://broadinstitute.atlassian.net/browse/CGSP-452

**Comment by cgpreston** [comment]
Signed off by stakeholders, closing. This was finished and reported as such for the Dec 21 -March 22 cycle.
