### ISSUE TITLE
Changes to the "Affiliation" field of the VCI/GCI ClinGen Curation Users screen

### ISSUE THREAD

**Issue by clarissaklein** [ClinGen/gene-and-variant-curation-tools#162]
Located at [https://curation.clinicalgenome.org/users/].

One change mentioned in earlier ticket #159 
and one new one:

- Add text wrapping to "Affiliations" field
- Automatically sort entries in "Affiliations" field by numerical, ascending value (e.g., automatically sorting 10003, 10002, 10004, and 10001 to 10001, 10002, 10003, 10004)

**Comment by wrightmw** [comment]
@clarissaklein this has now been released :-)
