### ISSUE TITLE
Improve Hypothes.is linkouts from the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#167]
V1 was released in https://github.com/ClinGen/gene-and-variant-curation-tools/issues/22 (#22)

This ticket is for further updates, e.g. currently the linkouts to Hypothes.is are not optimal as they do not link to all of the papers. Some work needs to be done by the clingen community curation database.

**Comment by markmandell** [comment]
Made the change in March 2024 to display multiple annotations in Hypothesis via our linkouts. We did most of the correspondence in Slack with Courtney and confirmed with her before releasing on March 18th, 2024
