### ISSUE TITLE
Restrict gene curation to GCEPs only

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#17]
The GCI was set up as a community curation tool, similar to the VCI, however it is now solely used by GCEPs. This ticket is to restrict access to the GCI so that it can only be edited by GCEPs.

Ability to create GDMs restricted to GCEPs (completed Dec 2020)
Ability to edit GDMs restricted to GCEPs:
Currently under discussion/scoping. Short term, only allow editors logged in as GCEPs to make any edits in the GCI. Longer term, make each GDM owned by a GCEP and then only that GCEP can edit it until the ownership is changed.

Replaced https://github.com/ClinGen/clincoded/issues/2289

**Comment by cgpreston** [comment]
SP ticket: https://broadinstitute.atlassian.net/browse/CSP-162

**Comment by cgpreston** [comment]
This was finished and reported as such for the Dec 21 -March 22 cycle.
