### ISSUE TITLE
"About us" page within header

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#174]
On our curation tools site (curation.clinicalgenome.org) generate an "About us" in the header pulldown, which links to a page that shows information on ClinGen and the Stanford ClinGen team.

**Comment by wrightmw** [comment]
Add "About Us" as option in the Help header pulldown.

Rearrange list so it reads in this order:
Contact Helpdesk
Help - VCI/GCI
SOP - VCI
SOP - GCI
GeneTracker
Terms of Use
About Us

And link “About Us” to  https://clingen.gitbook.io/vci-gci-docs/about-us/about-us

**Comment by markmandell** [comment]
Merged to prod
