### ISSUE TITLE
Gene curation SOPv9 updates

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#178]
Add SOPv9 as option to SOP pulldown in GCI. Make SOPv9 the default.

Export structure for SOPv9 is the same as SOPv8, and there are no other changes required in the GCI UI. We need to work with the website team to let them know to expect SOPv9 in our exports to the website and that the display format will be the same as SOPv8.

https://broadinstitute.atlassian.net/browse/CGSP-458

**Comment by cgpreston** [comment]
As agreed on April 14th, we will make this change in mid-May, to be live by June 1. 
https://broadinstitute.atlassian.net/browse/CGSP-458
