### ISSUE TITLE
Capture and disseminate VCEP curation reasons

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#180]
Capture the needed  information as to the reason why a VCEP is performing a curation 
- one possible suggestion is to add a modal in the VCI when a user is initiating an interpretation 
    - Determine user experience for this modal and the information being captured 
- The modal would ask the curator to identify which reason(s) they were curating that variant 
    - Determine if modal would be specific for VCEPs or would be for any VCI curation 
    - Determine menu of options as to why curation was taking place
    - Determine if we would allow users to backfill the modal for interpretations already in the VCI 
- There may be additional metadata to be captured at the same time for the report 
    - For example: The review status, clinical significance, last reviewed date, and number of submissions in ClinVar as of the date the interpretation was initiated. 

Provide an aggregate output report with this information for all VCEPs. 
- Determine the needed fields for the report 

To do: 

- [ ] Discuss with small group, propose a) the user experience b) the options c) the report output 
- [ ] Generate mockups 
- [ ] Review on tools call  

Relates to ticket #209 

SP ticket: https://broadinstitute.atlassian.net/browse/CGSP-460

DRAFT mockups: https://docs.google.com/presentation/d/1qQF9Xvx7XUGgHNOGt8f9QSgaiZ0LMlKy1G-YbTiPBXI/edit#slide=id.p

**Comment by cgpreston** [comment]
Note there maybe a companion process for the gene curation workflow, but it's unclear where that should live (GCI vs GT)

**Comment by wrightmw** [comment]
Changed title to same as SP ticket.

**Comment by wrightmw** [comment]
Example reasons:
- In EP scope
- Request from Stakeholder
- Required due to timing
- New evidence
- Error (affecting classification and/or scoring)
- SOP Framework change

**Comment by cgpreston** [comment]
Note: after October 2022 joint VCI/GCI call an ask made was for the users to put together example reports so that we can be sure the reasons captured meet their needs.

**Comment by wrightmw** [comment]
Closed and merged into https://github.com/ClinGen/gene-and-variant-curation-tools/issues/318
