### ISSUE TITLE
Remove duplicated GDM 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#190]
The Antibodies Deficiency (10080) GCEP have two entries for TNFRSF13C on their dashboard, both of which have identical MONDO terms and MOIs. They are asking that the "in progress" one be removed from the dashboard (either entirely deleted or it could be moved to the 10000 affiliation). I tried and it cannot be removed using the transfer curation tool. It also gives an error message if you follow the link: 

See this link: https://curation.clinicalgenome.org/curation-central/df88ef1d-5396-42e9-81c7-8e92fcadf05

<img width="1208" alt="Screen Shot 2022-04-15 at 1 34 19 PM" src="https://user-images.githubusercontent.com/46766411/163629626-9f901e9c-8d64-4ed3-873c-f655eef65168.png">
5

**Comment by gcheung-SF** [comment]
The "in progress" TNFRSF13C GDM has been removed now.  Thanks.

**Comment by wrightmw** [comment]
Done... .thank you @gcheung-SF
