### ISSUE TITLE
Change MONDO terms 

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#191]
Case 1
GDM: ABCD1- X-linked adrenoleukodystrophy X-linked inheritance
Current MONDO: MONDO:0018544 - X-linked adrenoleukodystrophy
New Mondo Terminology: MONDO:0018544 - adrenoleukodystrophy

Case 2
GDM: SCP2 - leukoencephalopathy-dystonia-motor neuropathy syndrome - Autosomal recessive inheritance
Current MONDO: MONDO:0013391 - leukoencephalopathy-dystonia-motor neuropathy syndrome
New Mondo Terminology: MONDO:0013391 - sterol carrier protein 2 deficiency

**Comment by gcheung-SF** [comment]
Matt, I have changed the MONDO terms.  Please check it out and let me know if there's other issues.  Thanks.

**Comment by wrightmw** [comment]
Thanks @gcheung-SF :-)
