### ISSUE TITLE
Other variant type homozygous scores

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#193]
Investigate other variant type homozygous scores. Mito GCEP have an example of a score that didn't double up from 1.5 to 3.

**Comment by gcheung-SF** [comment]
The total adjusted score is 1.5 because that's the max/upper limit for MOI = AR, Variant Type = "Other Variant Type".  The max score is 1.5 no matter if the variant is de novo and functional data support.  If this is not correct, please let me know and I can change it.  Thanks.
