### ISSUE TITLE
Documentation: Helpdesk FAQs and email templates 

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#196]
Generate Helpdesk documentation based on standard responses to helpdesk requests. Use this doc to generate FAQs for the interfaces.

**Comment by clarissaklein** [comment]
Am working on a template document updating Christine's old template document for common Helpdesk requests - will share it with Rachel, Ingrid, and Christine when it is done.

**Comment by wrightmw** [comment]
Excellent! Thanks @clarissaklein

**Comment by cgpreston** [comment]
@clarissaklein, do you think we can close this?

**Comment by clarissaklein** [comment]
Yes!
