### ISSUE TITLE
Investigate conservation scores not displaying

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#206]
Reported by a user over a few days, also confirmed by Christine: 

1. It appears most of the conservation scores (except GERP++) in the VCI are not displaying, even when they exist in our source. 
     * Example variant: CA000138
    * Myvariant.info output: http://myvariant.info/v1/variant/chr17:g.7675999A%3ET?assembly=hg38&format=html
    * VCI display linked below
<img width="908" alt="Screen Shot 2022-05-20 at 9 56 41 AM" src="https://user-images.githubusercontent.com/46766411/169576767-11d25f21-f9b6-4d97-a5b4-2f7c78717eb5.png">

**Comment by wrightmw** [comment]
![Screen Shot 2022-05-24 at 9 38 24 AM](https://user-images.githubusercontent.com/15131169/170087843-3343b264-f470-4e63-b847-e78d9541e357.png)

**Comment by kilodalton** [comment]
The API we need to display those scores changed as a result of MyVariant.info changing the parser for dbNSFP4.2 in this Pull Request:
 - https://github.com/biothings/myvariant.info/pull/123 (June 2021)
 
 This changed fields we depend on as seen in this screen captures from the PR above:

- **phylo => phylop**
<img width="745" alt="image" src="https://user-images.githubusercontent.com/1878194/171224087-1e78810b-abc0-495a-9e27-68abbb12af3e.png">


- **phastcons**
<img width="751" alt="image" src="https://user-images.githubusercontent.com/1878194/171224188-84cd54d6-ad51-4c5e-aea2-4648e90bef5f.png">


- **SiPhy**
<img width="622" alt="image" src="https://user-images.githubusercontent.com/1878194/171224547-e99f9228-3abb-40f9-9696-347e533d87b5.png">


_Note: Work on this is in progress_

**Comment by markmandell** [comment]
Fixed in another issue that was reported by Deb
