### ISSUE TITLE
CIViC links in the VCI 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#207]
The CIViC links in the VCI are no longer working, it looks like it may be related to CIViC's recent update.  It also looks like they revamped the API for their 2.0 release. 

Example:  CA126713
The VCI is currently directing to the URL: https://civicdb.org/events/genes/19/summary/variants/33/summary#variant
The CIViC link to this variant is now:  https://civicdb.org/variants/33/summary

**Comment by wrightmw** [comment]
Query ticket created in CIViC GitHub: https://github.com/griffithlab/civic-v2/issues/534

**Comment by cgpreston** [comment]
@kilodalton, the Baylor team was inquiring on the status of this ticket, they are presenting CIViC Tuesday at CCG and are trying to plan.
