### ISSUE TITLE
Approval date is incorrect in ClinVar submitter service

### ISSUE THREAD

**Issue by larrybabb** [ClinGen/gene-and-variant-curation-tools#208]
Sharing from @marinadistefano on 5/16/22 reported to the clinvar submitter service tool github repo [issue #35 here](https://github.com/clingen-data-model/clinvar-submitter/issues/35)

> The ClinVar submission generator is taking the date that I saved it as approved (e.g. today’s date) instead of the actual approval date. When I went to check on this in the eRepo, it’s the same problem.
> 
> Here’s an example: https://curation.clinicalgenome.org/variant-central/fa2cb91c-ba30-4b0c-a7b5-2d3cd884ef28/interpretation/88d051fa-2e2f-4648-8461-90b03b59dca0
> 
> And the eRepo link:
> https://erepo.clinicalgenome.org/evrepo/ui/interpretation/88d051fa-2e2f-4648-8461-90b03b59dca0

**Comment by larrybabb** [comment]
@bryanwulf @kilodalton I think we should have a one-off meeting to discuss this. While I hope/suspect there's a simple fix for this it does shine a light on the co-dependency that these external transformation tools have on the internal structure of you json.  This will become increasingly common with the work that Tristan and Terry have been doing for the past year on standardizing the output of the GCI too. The VCI transformation service was the first effort at using an external team (Broad/Geisinger) to standardize an internal format (VCI/Stanford).  We should work together to continue to both benefit from the shared responsibilities here and make sure we have a very high degree of communication around these touchpoints.

**Comment by cgpreston** [comment]
@larrybabb , we are currently actively investigating this issue.

**Comment by larrybabb** [comment]
@cgpreston please let me know how progress is going on this when you get a chance. thank you.

**Comment by larrybabb** [comment]
@cgpreston I think we could potentially get this fixed sooner than later if we look at the VCI-Transformation service that @bryanwulf stood up on AWS and which the VCI uses internally to convert your internal VCI json records into the SEPIO form that is used both by the eRepo and the ClinVar submitter.  I presume the approval date is in the VCI record and we simply need to map it correctly to the SEPIO structure in order to get the proper date to be exposed in the public message.

**Comment by kilodalton** [comment]
@larrybabb we will work together with you on this as we plan next steps.

**Comment by wrightmw** [comment]
@larrybabb is this fixed for you now?

**Comment by larrybabb** [comment]
@wrightmw did @bryanwulf update the VCI to expose the "final approval date" when it was older than the date the "approval" button was pushed and saved in the VCI? If he did that, then he (or I) would need to also update the VCI-transformer to pick up the "final approval date" (assuming he added a new attribute to the vci interprettion json output). But if @bryanwulf simply modified the vci interpretation json format to include the "final approval date' in place of the existing approval date whenever it is older (or different) then it, then it should all be working. 

So, the short answer to your question is where and what has @bryanwulf done thus far to get the "final approval date" exposed and/or available to the vci-transformer service.

let me know if any of that doesn't make sense.

**Comment by wrightmw** [comment]
@larrybabb ... @bryanwulf will answer your questions, but we should have a huddle with you, Bryan, me and Karen to discuss to make sure you have everything you need.

**Comment by bryanwulf** [comment]
@larrybabb The user-selected "final approval date", along with the system's approval date that records when the user approved the interpretation, have been exposed from snapshots created since a code update went live mid-July 2022 (in response to https://github.com/ClinGen/gene-and-variant-curation-tools/issues/204). For snapshots created before the code change (starting from early-December 2020), these dates weren't saved in the expected location and, consequently, weren't sent to the VCI-transformer.

For the example problem interpretation, redoing the approval and publish process (including selecting a "final approval date") would create new snapshots and correct the approval date at the eRepo. Other potential solutions are under review, but this one would provide the most immediate resolution.

**Comment by larrybabb** [comment]
I've verified the fix works as described above in the curation-test instance. I'll work with @marinadistefano to have her verify as well and provide her with the instructions to fix the historical errors.

**Comment by wrightmw** [comment]
Thanks @larrybabb

**Comment by marinadistefano** [comment]
Bryan had provided a problem hearing loss variant list and I just tried to unpublish, reapprove the variant, and reapprove and republish and it still has the same date problems in the eRepo, so I do not think that this error is fixed, at least on the eRepo side.

https://curation.clinicalgenome.org/variant-central/cad19c6a-4fcc-4d8f-8e66-54b590c82592/interpretation/fd54e511-37fc-437e-bf54-4757947ec10f/

@larrybabb @wrightmw @bryanwulf

**Comment by marinadistefano** [comment]
I realized that the eRepo just takes a bit of time to update their published record and this issue is indeed fixed. I am going to close the ticket.
