### ISSUE TITLE
Update affiliations July 2022

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#217]
The VCEP for affiliation 50050 has been step 4 approved, please enable publishing 

As part of this work: 

1. Added publishing for 10050 (DICER 1) 
2. Added user Sheng-An as an approver for CDH1 (10014) 
3. Added affiliation DDC (Dopa Decarboxylase)- affiliation 10118 
4. Added affiliation HLA - affiliation 10119
5. Added affiliation Rady's Children's Institute for Genomic Medicine - affiliation 10120

**Comment by cgpreston** [comment]
Ideally this would be completed by the end of the month (June 2022).

**Comment by cgpreston** [comment]
@bryanwulf, if possible could this be prioritized higher? The VCEP is interested in publishing soon. Many thanks.

**Comment by bryanwulf** [comment]
@cgpreston Sure... I'll take care of this request, along with other outstanding affiliation updates, soon.

**Comment by cgpreston** [comment]
@markmandell , I revised this ticket to list the work I'm aware you did, can you double check the list and let me know if anything is missing? Thank you!!

**Comment by markmandell** [comment]
The list looks correct, thanks for compiling everything Christine!
