### ISSUE TITLE
Hypothes.is integration with the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#22]
Automated integration of Hypothes.is annotations into the VCI

This ticket replaced https://github.com/ClinGen/clincoded/issues/2000

Dependency on bringing in Hypothesi.s annotation data via the LDH.

Currently being scoped by Stanford, Baylor and UNC.

**Comment by wrightmw** [comment]
Links with https://github.com/ClinGen/gene-and-variant-curation-tools/issues/21

https://broadinstitute.atlassian.net/browse/CSP-10

**Comment by cgpreston** [comment]
V1 of this was released in late 2021.

**Comment by kilodalton** [comment]
> V1 of this was released in late 2021.

Can this ticket be closed then?
