### ISSUE TITLE
Amend scoring of two variants to 3.0 points for all variant types

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#220]
When two variants are scored, they should be summed to 3.0 points for all variant types.

**Comment by gcheung-SF** [comment]
Changes is now on prod.

**Comment by courtneythaxton** [comment]
Awesome @gcheung-SF! thanks for getting this done.

**Comment by wrightmw** [comment]
Released. Thanks @gcheung-SF
