### ISSUE TITLE
Update MONDO terms

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#229]
MONDO_0009613 was originally labelled as "vitamin B12-responsive methylmalonic acidemia type cblA" but the label has been changed to "methylmalonic aciduria, cblA type". 

MONDO_0009614 has been updated  from "vitamin B12-responsive methylmalonic acidemia type cblB" to "methylmalonic aciduria, cblB type".

**Comment by gcheung-SF** [comment]
The disease terms have been updated on prod site.
