### ISSUE TITLE
Gene Tracker & GCI integration

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#23]
1) Transferring ownership of GDMs
From https://github.com/ClinGen/clincoded/issues/1607
Curator suggestion: to be able to transfer gene-disease records from one affiliation to another within the GCI.

Creating permissions for the coordinators to transfer records to affiliations.

A curator may do many novel gene-disease associations in which someone else acts as expert, but in future they could transfer these to an affiliation with individuals with that expertise.

To transfer records within affiliations, or open them up to editing by more than one affiliation.

Note: This may be useful for syndromic genes, in which experts in different parts of the phenotypic spectrum of the syndrome may want to weigh in on evidence scoring.

**Comment by cgpreston** [comment]
Scoping and work complete , epic with specific deliverables at https://broadinstitute.atlassian.net/browse/CGSP-401
