### ISSUE TITLE
Add new organisms to non-human model organism pulldowns

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#237]
Add organisms to the non-human model organism pulldowns in Experimental Data>Model Systems and Experimental Data>Rescue

Organisms to add:
Trypanosome (Trypanosoma brucei) 5691 
Tetrahymena (Tetrahymena thermophila) 5911

**Comment by wrightmw** [comment]
@markmandell  Here are more to add at the same time:

Organisms to add:
Slime mold (Dictyostelium discoideum) 44689 
Tetrahymena (Tetrahymena pyriformis) 5908
Killifish, Atlantic (Fundulus heteroclitus) 8078 
Killifish, Turquoise (Nothobranchius furzeri) 105023

**Comment by ikeseler** [comment]
I changed the GitBook help docs to no longer mention a specific number of model organisms, and added that new organisms can be added upon request.

**Comment by markmandell** [comment]
Merged to prod
