### ISSUE TITLE
GCI "interacting genes" forced capitalization 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#248]
In the GCI if you do the following: 
1.    Add experimental evidence 
2.    Select "protein interactions" from the pull down menu 
3.    Go to the "Interacting gene(s) ([HGNC](http://www.genenames.org/) symbol):" required field 

You will NOT be able to enter lower case values into the HGNC field. While normally this is correct, there are a few examples ("C9orf72" being the use case that identified this issue) where HGNC does include lower case values, and curators are blocked from then entering those genes. Please fix. 
<img width="1369" alt="Screen Shot 2022-09-15 at 1 23 09 PM" src="https://user-images.githubusercontent.com/46766411/190505209-ada2ab25-5016-44b5-b64a-aecf29149b06.png">

Note: to start a GCI curation you also cannot enter lower case values, however it recognizes "C9ORF72" and then transposes it to "C9orf72" in the interface.... can we do the same thing for the "interacting genes" section?

**Comment by markmandell** [comment]
Given that we recognize this gene when starting a GCI curation as Christine mentions, I am sure we can do the same for this input in experimental evidence 👍

**Comment by liammulh** [comment]
I think I have a patch in https://github.com/ClinGen/gci-vci-aws/commit/4092d0e244564e5a4fd34a2795411c42f3e25c2f. I will deploy this in my next batch of fixes.

**Comment by liammulh** [comment]
This is working on the test site.

**Comment by liammulh** [comment]
This is now in prod.
