### ISSUE TITLE
VCI not loading

### ISSUE THREAD

**Issue by msingerb** [ClinGen/gene-and-variant-curation-tools#253]
My VCI pages and dashboard are not loading. I get the continuing loading wheel. I have tried restarting my computer but nothing has changed. The links I have tried are below:

https://curation.clinicalgenome.org/dashboard/
https://curation.clinicalgenome.org/variant-central/2613fc72-cf41-4968-8128-9371c6536a4d/

Here is a screenshot of what it looks like.
![image](https://user-images.githubusercontent.com/47390031/193830802-7440501c-2bd1-4a89-889e-a98995e5266e.png)
![image](https://user-images.githubusercontent.com/47390031/193830872-5e10590d-2696-4fd9-ae5f-329891b12b15.png)

**Comment by markmandell** [comment]
Hi @msingerb, thanks for reporting this issue. Please try clearing your browser cache and logging back in, it could be the browser as I am having success loading those links. Let me know if it still is not working and we will investigate further.

**Comment by msingerb** [comment]
Hi Mark. I tried clearing my cache and now im getting an error signing in
![image](https://user-images.githubusercontent.com/47390031/193895414-0ef98e58-f072-4fa2-a2c3-83ca923ff346.png)

**Comment by markmandell** [comment]
@msingerb apologies for these errors. Would you be available for a quick call to see if we can fix the issue together? My Stanford email is markmand@stanford.edu, we can setup a call via email. Thank you!
