### ISSUE TITLE
Warning message if genetic evidence is zero points

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#256]
If there are zero genetic points in the classification matrix, then if a curator goes to save it as provisional then a warning message should pop up that asks them if they want to proceed even though there is not genetic evidence scores.... once clicked to say yes, they can continue.

**Comment by wrightmw** [comment]
@ErinRiggs @courtneythaxton @marinadistefano

**Comment by liammulh** [comment]
Patch added in https://github.com/ClinGen/gci-vci-aws/commit/53669ad86dd33d9a42ad07a3c04903eefb50c65b. I used the `window.confirm` browser method.

**Comment by liammulh** [comment]
This is live in the production website.
