### ISSUE TITLE
DRAFT: Affiliation updates November 2022

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#265]
DRAFT: we are collecting affiliation update requests starting Nov 7 2022 here for the next update

Please update the following affiliations: 

1. Name of affiliation 10070 (marked in spreadsheet) to "Congenital Anomalies of the Kidney and Urinary Tract"
2. Add affiliation 10137 
3. ~~Add "Broad Rare Disease Group" with ability to publish to the GCI (hold off on this third item until we get sign off from GCI proxies)~~

**Comment by wrightmw** [comment]
There is a 4th one... add Interstitial Lung Disease affiilation.... am I too late for this ticket @markmandell @cgpreston? If so we can create a separate ticket for it... it's not urgent.

**Comment by markmandell** [comment]
@wrightmw not too late! Can add it to the PR 👍

**Comment by cgpreston** [comment]
We did NOT add GCI access to the Broad Rare Disease group.
