### ISSUE TITLE
Test new ClinVar submission service 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#268]
We want to create a test environment for proxies to test the changes made to the ClinVar submission service (this was needed as ClinVar changed their submission formats) 

 The service that has been updated is at https://clinvar-submitter.stage.clingen.app/api/v1/submission.

**Comment by kilodalton** [comment]
@wrightmw @bryanwulf We need to create a development instance to test individual and batch ClinVar submission using the above staging version of the service as soon as possible.

Changes are needed to support the recent change in ClinVar submission structure. Please work with Larry.

**Comment by bryanwulf** [comment]
Although we use a slightly different URL (http://clinvar-submitter.stage.clinicalgenome.org/api/v1/submission), the current default for all non-production versions of the VCI is to send requests to the "staging" version of the ClinVar submitter service. This was confirmed for https://curation-test.clinicalgenome.org by comparing the ClinVar submission data it generated against results from https://curation.clinicalgenome.org (the data generated on curation-test had two fewer columns, matching Larry's description of the changes made to the service).

**Comment by cgpreston** [comment]
I believe this was done.
