### ISSUE TITLE
Make disease required for publishing in the VCI

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#273]
After discussion with the VCI proxies on 12/5/22: 

A disease should be required for curations being published to the ERepo, the suggestion is to block ERepo publishing (and have a user notification explaining why) for ClinGen affiliation curations lacking a MONDO/disease term. 

Notes: 
1. This same logic should NOT apply to the MOI, the proxies were able to think of multiple use cases where a MOI not being added was desired. 
2. To minimize the burden on non-ClinGen affiliations and for a few use cases the proxies felt that blocking publishing (but not approval) was the correct step for this logic.

**Comment by wrightmw** [comment]
When a user attempts to publish the ERepo, we need to check if there is an associated disease. If there is no disease, then publishing to the ERepo is stopped and the following warning message is displayed:
A disease must be associated with a classification in order to publish to the ClinGen Evidence Repository

**Comment by liammulh** [comment]
I believe I have a fix in https://github.com/ClinGen/gci-vci-aws/commit/59885e767023bcacbd1c014b282e66bd9eafd890.

**Comment by liammulh** [comment]
Note to self. if something related to this comes up again, here is how to test this manually:

1. Navigate to a variant that doesn't have an associated disease.
2. Click "View Summary".
3. Scroll down a bit and there should be a teal button to either un-publish from the evidence repository or publish to the evidence repository. See the screenshot below.

<kbd>
<img width="500" alt="gavct-issue-273" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/60749003/a0fa8d8e-f6f9-4049-acaa-1fdf52599b67">
</kbd>

**Comment by liammulh** [comment]
This seems to be working on the test site.

**Comment by liammulh** [comment]
This is now in prod.

**Comment by liammulh** [comment]
There is probably an issue with the patch I added. Here is a help desk email:

> I am trying to submit a variant NM_000162.5(GCK):c.1121T>A (p.Val374Glu) from the Monogenic Diabetes affiliation.  I am having two issues:

> 1. I am getting a message that a classification is needed, but there is a classification, likely pathogenic.  I can't submit the variant.  This may be because we have previously modified the classification, and then changed back to automatic.  So I tried manually selecting likely pathogenic and I'm still getting a message that I need a classification.
> 2. [...]

> Now having the same issue with NM_000162.5(GCK):c.1113C>A (p.Cys371Ter) and realizing the issue may be that the VCI thinks the disease is missing.  (Actual message:  "A disease must be associated with a classification in order to publish to the ClinGen Evidence Repository").  But the disease is not missing.  It is monogenic diabetes (MONDO:00015967).  Please advise.  Thank you.

**Comment by liammulh** [comment]
I added the same disease:

<kbd>
<img width="350" alt="disease" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/60749003/e85ad5b5-f433-4124-a91f-8bddb620e235">
</kbd><br/><br/><br/>

And then I added some log statements to my `hasDisease` function:

```
const hasDisease = interpretation => {
    console.log(`interpretation?.disease !== undefined is: ${interpretation?.disease !== undefined}`);
    console.log(`interpretation?.disease !== null is: ${interpretation?.disease !== null}`);
    console.log(`typeof interpretation?.disease === 'object' is: ${typeof interpretation?.disease === 'object'}`);
    console.log(`Object.keys(interpretation?.disease).length > 0 is: ${Object.keys(interpretation?.disease).length > 0}`);
    return interpretation?.disease !== undefined
           && interpretation?.disease !== null
           && typeof interpretation?.disease === 'object'
           && Object.keys(interpretation?.disease).length > 0;
};
```

I'm seeing the following in the console:

```
interpretation?.disease !== undefined is: false
interpretation?.disease !== null is: true
typeof interpretation?.disease === 'object' is: false
Uncaught TypeError: Cannot convert undefined or null to object
```

So it seems like `interpretation.disease` is `undefined`.

**Comment by liammulh** [comment]
I think I've discovered the problem. There's a [line](https://github.com/ClinGen/gci-vci-aws/blob/eb44864c77ad20d7ae8fdea550653447a57f57ba/gci-vci-react/src/components/provisional-classification/publish.js#L442) that indicates the interpretation object is actually in props. I am not sure why I thought it was in state.

**Comment by liammulh** [comment]
I need to manually test my patch:

- [x] Test positive case where there is a disease. Ensure you can publish to the evidence repository.
- [x] Test negative case where there is no disease. Ensure you can't publish to the evidence repository.

**Comment by liammulh** [comment]
So far as I know, there have been no further issues from our users. Closing.
