### ISSUE TITLE
Remove approvers from Brain Malformations EP

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#281]
Please remove all approvers for the Brain Malformations (10020) EP, this will affect both the VCEP and GCEP.

**Comment by wrightmw** [comment]
@cgpreston Just to clarify, is this task only to remove the Approvers list from the Brain Malformations (10020) EP affiliations file? It is not to remove existing selections of Approvers from saved snapshots in the VCI.

**Comment by cgpreston** [comment]
@wrightmw, yes the ask is to remove the approvers going forward.

**Comment by markmandell** [comment]
merged to prod 12/15/22
