### ISSUE TITLE
Display LitVar in the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#298]
Ostensibly within a variant record we need to search the LitVar API to see if there are associated papers for that variant. If so, we need to return these data as a new line in the Other Resources table.

**Comment by markmandell** [comment]
Related to #72 

Work on this ticket includes: 
Provide/display LitVar link for variant in basic info => other external resources table

**Comment by markmandell** [comment]
Merged to production 2/9/23
