### ISSUE TITLE
Ability to select Case-Control evidence as Review or Contradictory

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#30]
https://broadinstitute.atlassian.net/browse/CGSP-514

Currently there is no way to score if a paper contradicts a gene-disease relationship for Case-Control.

It would be good to add the "Select Status" modal in scoring for Case-Controls, as it allows the user to flag the evidence to Score (in which the scoring range is provided), Review (for when expert opinion is required), or contradicts. 

The main reason is being able to score contradictory evidence in which papers suggest NO association of genes of interest in the disease of interest. 

Please see the attached image for the modal to add for scoring and flagging evidence in Case-Control. the addition of this modal should work the same for an Individual or Family info from Case-level genetic, in which flagging as contradictory allows the flag on the final Classification matrix.

<img width="960" alt="Screen Shot 2019-09-17 at 7 55 18 PM" src="https://user-images.githubusercontent.com/32530005/65087941-95495680-d985-11e9-8e42-0f518e107ac8.png">

This ticket replaced https://github.com/ClinGen/clincoded/issues/2038

**Comment by wrightmw** [comment]
Would like following scoring options:
1) Score, Review, and Contradicts are all options on first pulldown
2) i)If you select Review or Contradicts then these are saved, whereas ii) if you select Score then you get the current scoring pulldown to select the score and save it.

Also, if Contradicts is selected, it should indicate contradictory evidence is present on the classification matrix page (see first image), as well as in the Evidence summary, top of the page summary.

<img width="893" alt="Screen Shot 2019-09-17 at 8 13 37 PM" src="https://user-images.githubusercontent.com/32530005/65088511-b743d880-d987-11e9-8fc6-978636ea90d7.png">

**Comment by ikeseler** [comment]
Updated the help docs and will remind the GCI proxies to update the SOP in the next version.
