### ISSUE TITLE
Require GeneTracker ID to start a new GDM

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#300]
This functionality would require the curator to enter a GeneTracker ID to confirm they have done the pre-curation, in order to create a new GDM. We need to confirm the GeneTracker ID is valid.  If it is, the same rules for duplicate entries as currently in place will still apply, i.e. we cannot create a duplicate GDM.

**Comment by ikeseler** [comment]
We need wording for error messages in these cases:
1 - The GT ID entered by the curator does not exist within the GT
2 - The GT ID entered by the curator exists, but the information does not match with the information in the GDM (different gene/disease/MOI?)
3 - The GT ID entered by the curator exists, but the record does not belong to the affiliation used by the curator

Proposed wording:
1: The GeneTracker precuration ID "xyz" is invalid. Please check for the correct ID in the GeneTracker[link].
2. The precuration information in the GeneTracker does not match the GDM you are trying to create. Please confirm the correct gene, disease and MOI information in the GeneTracker[link].
3. The GeneTracker ID you have entered belongs to a different affiliation. Please check that you are curating within the correct affiliation.
