### ISSUE TITLE
ClinVar Batch Submission- Edit Current Batch Acknowledgement 

### ISSUE THREAD

**Issue by rachel-shapira** [ClinGen/gene-and-variant-curation-tools#312]
In the Edit Current Batch modal, the textbox to enter "Confirm" seems to be case sensitive so "confirm" is not an accepted response. See attached screenshot from Demo Version. Please adjust setting so this field is not case sensitive. 

![Screenshot 2023-02-07 at 2 13 20 PM](https://user-images.githubusercontent.com/99292846/217343056-0822c4ba-29bc-4aeb-838d-0e19a08f6868.png)

**Comment by liammulh** [comment]
Patch added in https://github.com/ClinGen/gci-vci-aws/commit/cf65b2087b44ced9f552c05013eeae3feec770dc.

**Comment by liammulh** [comment]
This is live in the production website.
