### ISSUE TITLE
Support OLS v4 in GCI & VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#319]
Currently, for some diseases (e.g. MONDO:0100216) the current OLS lookup service is not working. This is because the EBI seems to have switched over to a new version called OLS4, see https://www.ebi.ac.uk/ols4

We need to updated to OLS4 in the GCI when:
1. creating a GDM
2. changing a disease

and in the VCI when:
1. adding or changing a disease

**Comment by markmandell** [comment]
Merged to production 4/17/23
