### ISSUE TITLE
Affiliation updates July 2023

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#333]
Please make the following affiliation updates: 
1. Update affiliation 10123 name From:  Systemic Lupus Erythematosus, To: Monogenic Systemic and Incomplete Lupus Erythematosus
2. Add affiliation 10147
3. Add affiliation 10148

Affiliation sheet: https://docs.google.com/spreadsheets/d/1IF9GiP8iiFx1CndgqdWNGx4A_uM2GsWnV7GSiUO33bs/edit#gid=2034898506

**Comment by liammulh** [comment]
These updates are now in prod.
