### ISSUE TITLE
Add link to VCEP standardized text in the help menu

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#334]
Add a link to the VCEP standardized text in the help dropdown menu.

- text "Standardized Text - VCI"
- url link: https://clinicalgenome.org/site/assets/files/6773/vcep_general_standardized_summary_text_v2_jan_11_2022.pdf

Suggestion is to place this above the Genetracker link, as so: 

<img width="263" alt="Screen Shot 2023-07-21 at 8 36 57 AM" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/46766411/436f4878-65ce-404c-a50c-86a30dca2a9c">

**Comment by liammulh** [comment]
Added in https://github.com/ClinGen/gci-vci-aws/commit/7520b965e708ef2df7e18642c04e11c0dcae1c3c. This will be published in my next batch of fixes.

**Comment by liammulh** [comment]
This is working on the test site.

**Comment by liammulh** [comment]
This is now in prod.
