### ISSUE TITLE
Colorize the Specification Document button in the VCI 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#337]
Background: When a disease or mode of inheritance are added the button turns from grey to a color. However the CSpec button does not have this experience. 

Please make it so the Specification Document button turns a color when a Specification Document is added to a curation (maybe a green color?). 
<img width="950" alt="Screen Shot 2023-09-18 at 2 32 08 PM" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/46766411/1ad4ee86-f7d2-4c2c-a576-96266d077d2a">

**Comment by markmandell** [comment]
<img width="1257" alt="Screenshot 2023-12-05 at 3 03 25 PM" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/45801431/9fda3982-4fd5-419c-a9eb-03525cf8e06d">
Screenshot of purple color decided for CSpec button

**Comment by markmandell** [comment]
Merged into production 12/6/23
