### ISSUE TITLE
Update publishing rights from the VCI to ERepo

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#339]
1. update "all" affiliation files to mark them as ClinGen or non-ClinGen... from now on we would capture this
    * use the 40000 numbers to determine ClinGen VCEPs
2. update the publish UI in the VCI so that if it is a ClinGen affiliation (as per new field above) and if that ClinGen affiliation has attached a valid CSpec doc, then they should just be allowed to publish to the ERepo
   * NOTE: either a valid CSpec OR a guidelines URL are acceptable, this will allow us to support older variants that do not have a CSpec document and some fringe use cases (such as retired variants).

For our helpdesk this means that going forward we will NOT add the guidelines name and URL (rows L & M in our affiliations spreadsheet) for VCEPs upon step 4 approval. 

Need to confirm these changes will be OK with ERepo team 

@cgpreston

**Comment by cgpreston** [comment]
@markmandell  can we close this?
