### ISSUE TITLE
Add Gene Curation SOP v10 as an option in the pull-down menu and make SOP v10 the Default by October 31st

### ISSUE THREAD

**Issue by bmpbowen** [ClinGen/gene-and-variant-curation-tools#340]
Filing this ticket as follow-up from the Gene Curation Small group meeting, where the following request was made:

- Confirm with the GCI team that they are ok with us releasing SOP v.10 on November 1, barring any major feedback from the Gene Curation Working Group on Wednesday.  This typically involves ensuring that SOP 10 is available in the SOP dropdown and becomes the default choice from November 1 onwards.  There may be other behind-the-scenes things that need to occur as well, though there are no major scoring or template changes so this should be minor.

- Once approved and posted to the website, update any links to SOP 9 on the GCI site/help documents to SOP 10.

-Once approved and posted to the website, update the link to the evidence summary templates to the final PDF that we will post on [clinicalgenome.org](http://clinicalgenome.org/).

**Comment by gcheung-SF** [comment]
@bmpbowen , changes is now on prod site.

**Comment by bmpbowen** [comment]
Closing as we are now onto SOPv11 ;)
