### ISSUE TITLE
Update the GCI to the new HPO API by Nov 29th

### ISSUE THREAD

**Issue by bmpbowen** [ClinGen/gene-and-variant-curation-tools#341]
HPO has a notification banner indicating they are making API changes: old url https://hpo.jax.org/app/data/ontology is moving to [https://ontology.jax.org](https://ontology.jax.org/api/hp/docs/)

We need to ensure that the GCI links out to the new API by November 29th anywhere the old url exists. 

<img width="906" alt="image" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/139911863/d2b5a4c3-1615-486b-b614-584e1f8aee5a">

Update HPO urls in individual, group, family, case-control, and anywhere else in the GCI.
<img width="900" alt="Screenshot 2023-10-12 at 12 22 26 PM" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/139911863/6c7fbbd2-7827-42a7-88fa-feb5c15dd89f">
<img width="785" alt="Screenshot 2023-10-12 at 12 24 16 PM" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/139911863/89f38683-950b-40bf-868e-eae5de8476fb">
<img width="636" alt="Screenshot 2023-10-12 at 12 26 08 PM" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/139911863/c8031726-b748-47fb-a902-dd8c4957cf6a">
<img width="1195" alt="Screenshot 2023-10-12 at 12 27 56 PM" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/139911863/e64a9cad-2c02-4c0f-9863-d78535ba330f">
<img width="1195" alt="Screenshot 2023-10-12 at 12 29 12 PM" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/139911863/2dfca99f-1fe5-463b-9e00-14f8e4221ff3">

**Comment by gcheung-SF** [comment]
GCI & VCI have been updated to use the new API but not links to HPO terms.

Just checked and the release date has been moved - "expect to fully switch by December 31, 2023 ... however term annotation endpoints have not yet been moved."
Need to check back and see if links change are needed.

**Comment by cgpreston** [comment]
@gcheung-SF , can we close this?

**Comment by gcheung-SF** [comment]
@cgpreston , just tested the changes and worked as expected.  I will just close it.
