### ISSUE TITLE
2023 wipe of the test site 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#347]
We annually wipe the test site of all curation data, the following needs to be done:
- [x] Send out an email to the user base reminding folks of the upcoming wipe (due week of Jan 5th - Christine) 
- [x] Wipe the site on Jan 18th (Bryan) 
- [x] Update the banner on the test site to state (Bryan)
`Note: This is a demo version of the site. Data entered will be deleted periodically, the next deletion is scheduled for December 18, 2024.`

**Comment by cgpreston** [comment]
This is happening in January to support a user request.

**Comment by markmandell** [comment]
Test site wipe completed, banner date updated
