### ISSUE TITLE
Investigate and update CiVIC link issue reported

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#349]
Reported by curator: 

Variants in CiVIC are not populating in the "other evidence resources" table, (example variant:  376015), it's worth noting that according to the CiVIC website: 

> PUBLIC NOTICE: CIViC v1 API TO BE DEPRECATED
> Oct 1, 2023
> The CIViC V1 REST API will officially be retired on November 1st, 2023. All CIViC integrations should transition to our new V2 GraphQL API. The new API is more powerful and provides access to the newest CIViC data model, features, and data. The easiest way to get started is to try out queries and browse the documentation in the [GraphiQL sandbox](https://civicdb.org/api/graphiql).

SP ticket: https://broadinstitute.atlassian.net/browse/CGSP-665

**Comment by liammulh** [comment]
I believe we can close this now. This was addressed in https://github.com/ClinGen/gci-vci-aws/pull/1436 and https://github.com/ClinGen/gci-vci-aws/pull/1432.
