### ISSUE TITLE
GCI: Score homozygous probands at 0.1. 

### ISSUE THREAD

**Issue by bmpbowen** [ClinGen/gene-and-variant-curation-tools#357]
Request from Gene Curation Small Group:

Add a 0.05 option to the GCI for homozygous probands, and include a tooltip to explain that homozygous probands get scored as 0.1

**Comment by bmpbowen** [comment]
<img width="882" alt="image" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/139911863/85a69941-08e0-4bc5-a9d6-ad1522b2cfd4">

**Comment by gcheung-SF** [comment]
Questions: 
1. So 0.05 score option is only available in following condition:
  Variant Type = Other Variant Type
  de novo = No
  Function Data = No
But not for other combinations (i.e. de novo = Yes)?
And the tooltip appears all the time or when user selects above and 0.05 point?

2. When MOI = Semidominant inheritance and proband is = "Biallelic homozygous" or "Biallelic compound heterozygous" then treat as AUTOSOMAL_RECESSIVE.  If user checks homozygous box, should same logic apply at this case?

**Comment by bmpbowen** [comment]
My apologies for the confusion generated by the sample screenshot. To answer the above questions:
1. I think we want the 0.05 option to appear for **all** homozygous variant types, not just "other variant type". 

- Re: de novo, most de novo variants occur in AD conditions in the heterozygous state. I don't think we would score a homozygous de novo variant but I'll confirm with the gene curation small group since there can be some very rare edge cases where one might think one or both of a proband's variants occurred de novo. They said it would be simplest to just leave the 0.05 option across all scenarios
- Re: functional data... functional data should not impact whether the 0.05 option applies. 
- Tooltip: we want it there all the time. 

3. When MOI - Semidominant and proband is biallelic homozygous or biallelic compound heterozygous, we also want to include the 0.05 scoring option.

**Comment by gcheung-SF** [comment]
Changes is now on live site.
