### ISSUE TITLE
GCI - limit reviewed/approval/published date to current and past date

### ISSUE THREAD

**Issue by gcheung-SF** [ClinGen/gene-and-variant-curation-tools#361]
From Deborah Ritter:

This gene on the page NIPBL has a curation date of 6/28/24. Are we in to futuristic gene curation now? :) This is a typo but not sure how it got in, at what point was a future date allowed in the system, I didn't track it back but wanted to alert. It also seems the curation was done in 2018, and for some others on the page too, the classification date shown on the website is not the classification date in the text of the summary. But most are in the ballpark of that date, this one is very off.

(This isn't my GCEP, was looking for LZTR1 in Prenatal GCEP because we have an overlapping curation, but they haven't curated it yet. While on the page I saw the date and wanted to report.)

-----------------------------------------------------------

Fix: Update date selector to disallow future date to be selected.

**Comment by markmandell** [comment]
Merged into curation-test and prod
