### ISSUE TITLE
Add ferret as a model organism in the GCI

### ISSUE THREAD

**Issue by bmpbowen** [ClinGen/gene-and-variant-curation-tools#363]
We received a request from a GCEP to add ferret as an option for model organisms, as this is a common species in that affiliation and it currently presents a blocker to publishing one of their curations. 

Ferret (Mustela putorius furo) 9669

Taxonomy ID: 9669
Reference: 
https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi

**Comment by wrightmw** [comment]
Transposed to the pulldown format in the GCI this would be:
Ferret (Mustela putorius furo) 9669

**Comment by wrightmw** [comment]
These others could be added at same time:
Hydra (Hydra vulgaris) 6087
Anole (Anolis carolinensis) 28377
Aspergillus (Aspergillus nidulans) 162425
Neurospora (Neurospora crassa) 5141
Marmoset (Callithrix jacchus) 9483

This affects two Experimental pulldowns... one in Rescue, the other in Model Systems

**Comment by gcheung-SF** [comment]
The 6 model organisms are added to prod site.
