### ISSUE TITLE
Make Final Approval Date a Required Field

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#364]
Copy functionality in the GCI, so that curators are required to select a Final Approval Date in order to save an Approval in the VCI.

See screenshot of current GCI experience to replicate: 
<img width="186" alt="Screen Shot 2024-04-10 at 2 21 55 PM" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/46766411/ce0aa747-0440-422d-b07e-37e3a0b34ff0">

SP ticket: https://broadinstitute.atlassian.net/browse/CGSP-722

**Comment by wrightmw** [comment]
Needs to be added to SP board.

**Comment by wrightmw** [comment]
Make sure future date cannot be entered. @markmandell maybe it make sense to do the GCI update on not allowing future dates at same time?: https://github.com/ClinGen/gene-and-variant-curation-tools/issues/361

**Comment by markmandell** [comment]
Merged into curation-test and prod
