### ISSUE TITLE
Update strengths to certain criteria codes in the VCI 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#365]
Update the VCI criteria code strengths to add strengths that are a part of the existing framework.

Specified changes needed: 
    * Add PS4_VeryStrong to VCI
    * Add PS3_VeryStrong to VCI
    * Add PM6_VeryStrong to VCI (caveat, PM6_VS should never be combined with PS2_VS) 

[Mockups](https://docs.google.com/presentation/d/1biKVKZVUHzuv5s86NxKIsk9zZ-7E-JmySaTVrvtXlXY/edit?usp=sharing)

Associated Documentation: 
[Variant Curation - VCI Options](https://docs.google.com/presentation/d/1UYvB21CUh_YltWdXskzbHHJKJFDlydHfHTpG4pIKnoY/edit#slide=id.g11809e98eef_0_6) 
[VCI Options](https://docs.google.com/spreadsheets/d/1heS9fPizdZt0_r6kgPqKKd1Gizm98b6cUUjRLqmD3MQ/edit#gid=0) 

 To do: 
    * Discuss w/ Baylor CSpec and ERepo work needed and timelines 
    * Update VCI and internal VCI pathogenicity calculator to include the codes 

Replaces #41 
SP ticket: https://broadinstitute.atlassian.net/browse/CGSP-674

**Comment by cgpreston** [comment]
Testing on 7/9/24 by PO and a VCI proxy was consistent with the specs provided regarding the UI display, the combining logic, and the ClinVar output. Once it's been confirmed the ERepo is prepared to accept the new strengths we can release.

**Comment by markmandell** [comment]
Merged to curation-test and production
