### ISSUE TITLE
Display more detail in the CSpec selection modal 

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#377]
This is a high priority CSpec-VCI v3 integration ticket, proposed to be done alongside #376 and #136

There are examples where affiliations have multiple CSpec documents with the exact same name  (VHL, ACTA1, and RYR1 for example).... which creates complications for the curators as the document name is what we show in the CSpec selection modal.

Discussed on the tools call 8/1/24: https://docs.google.com/presentation/d/15dWVGIFggZYYF4YHTLdZ1QrPKuqaGyhwbXKIc8KdkTw/edit#slide=id.g2f00bf21d74_0_10, there is a plan to add in an identifier in the CSpec, but this hasn't been finalized. 

We could explore other options of CSpec fields to display in the VCI, or await the update from the CSpec and then display the whole name. 

For ACTA1 and RYR1 the top-level difference is the mode of inheritance. 
For VHL the top-level difference (there are 3 documents) is the disease term(s). 

Possible solutions:
* Display the Disease and MOI in the modal 
* Add in links to the CSpec document. 

SP ticket: https://broadinstitute.atlassian.net/browse/CGSP-761

**Comment by cgpreston** [comment]
Next step: Discuss with proxies , possibly this could be combined with the work in #376

**Comment by markmandell** [comment]
merged to curation-test and prod
