### ISSUE TITLE
Add GCI Paper to banner on curation.clinicalgenome.org landing site

### ISSUE THREAD

**Issue by bmpbowen** [ClinGen/gene-and-variant-curation-tools#378]
Now that the [Wright et al 2024 paper](https://pubmed.ncbi.nlm.nih.gov/38663031/) is out, we should add an announcement banner to the curation.clinicalgenome.org landing page:

![image](https://github.com/user-attachments/assets/d3d4330c-9fb5-406a-97ae-c99bd8e14621)

Text: 
**Read our GCI paper!**

Curious about how our ClinGen gene curation systems work?
See our latest peer-reviewed publication in the
_Annual Review of Biomedical Data Science_:

Wright MW et al. Generating Clinical-Grade Gene-Disease
Validity Classifications Through the ClinGen Data Platforms.
2024 Aug;7(1):31-50. PMID: [38663031](https://pubmed.ncbi.nlm.nih.gov/38663031/)

**Comment by gcheung-SF** [comment]
Need to wait for final publish date for the banner.

**Comment by bmpbowen** [comment]
The publish date for the GCI paper has been updated and the banner can now go live.

**Comment by gcheung-SF** [comment]
New banner is now on live site.
