### ISSUE TITLE
Add Gene Curation SOP v11 as an option in the pull-down menu and make SOP v11 the Default by September 11th, 2024

### ISSUE THREAD

**Issue by bmpbowen** [ClinGen/gene-and-variant-curation-tools#379]
Once approved and posted to the website, update any links to SOP 10 in the GCI to SOP 11.

Once approved and posted to the website, update the link to the evidence summary templates to the final PDF that will post on [clinicalgenome.org](http://clinicalgenome.org/).

**Comment by gcheung-SF** [comment]
Should the "SOP - GCI" link under Help menu and SOP v# links in evidence summary be changed/updated?
Currently it links to https://www.clinicalgenome.org/curation-activities/gene-disease-validity/educational-and-training-materials/standard-operating-procedures/ but is redirected to https://www.clinicalgenome.org/curation-activities/gene-disease-validity/training-materials/.  Then there is a current SOP link.  Should this be kept as is in GCI?

It seems the current SOP link is https://clinicalgenome.org/docs/gene-disease-validity-standard-operating-procedure/.  Will this be updated and points to SOP v11?

**Comment by bmpbowen** [comment]
SOP v11 url: https://clinicalgenome.org/docs/gene-disease-validity-standard-operating-procedures-version-11/

**Comment by gcheung-SF** [comment]
Just checked that the SOP link on https://www.clinicalgenome.org/curation-activities/gene-disease-validity/training-materials/ now goes to SOPv11 so it's good as is.

**Comment by gcheung-SF** [comment]
Pushed to live site.
