### ISSUE TITLE
Display MANE Plus Clinical transcripts in Basic Info tab

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#38]
SP request: https://broadinstitute.atlassian.net/browse/CSP-183
Replaces https://github.com/ClinGen/clincoded/issues/2308

Add "MANE plus clinical" tags in the transcript table on the basic info tab. Example of gene with these transcripts is LMNA, also CDKN2A. 

---------Discussed 7/19/22-----------
For the transcript tables, the current logic is preferentially getting the transcripts from ClinVar, if not available there then the allele registry. Other data (exons and the MolC) are pulled from Ensembl. There may be a way to optimize this later, ideally the CAR would provide the exons and MolC and the VCI could pull from CAR for those tables unless unavailable (in which case ClinVar/Ensembl would be a backup pathway). 

For now the decision is made to maintain the current logic but support showing the MANE plus clinical and MANE select tags in the transcript tables.

**Comment by cgpreston** [comment]
testing: https://docs.google.com/spreadsheets/d/1zWWe33L1RptWKNVprlg-LY-d7GjBigckdZ5EtgSTamc/edit#gid=0
