### ISSUE TITLE
Add PM6_VeryStrong criteria code modifier to pull-down for PM6

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#46]
Request for a PM6_VeryStrong option to be added to the drop-down menu for PM6.

It is a valid option per SVI guidance: https://www.clinicalgenome.org/site/assets/files/8490/recommendation_ps2_and_pm6_acmgamp_critiera_version_1_0.pdf

![screen shot 2018-09-26 at 4 34 19 pm](https://user-images.githubusercontent.com/15131169/46115050-3a35b700-c1aa-11e8-838b-971cdafbaa54.png)

Replaces https://github.com/ClinGen/clincoded/issues/1787

**Comment by wrightmw** [comment]
If rolled out we'd probably need an OR between these criteria.

This ticket requires input from the SVI.

**Comment by cgpreston** [comment]
Retiring this in favor of #41
