### ISSUE TITLE
VCI UI updates

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#48]
Several updates are currently required to the VCI UI:

1) rename the "Save and View Evidence" button in the VCI after the search and select variant screen to "View Evidence" (replaces https://github.com/ClinGen/clincoded/issues/2303)

2) switch "pathogenicity" with "classification" (replaces https://github.com/ClinGen/clincoded/issues/2290)

When the VCI launched we used “pathogenicity” to describe the final ACMG category used (B/LB/VUS/LP/P), since then the field has moved on to using the term “classification”. A few sections of the VCI UI need to be appropriately updated. 

* For detailed mockups see here: https://docs.google.com/presentation/d/1Y6UCIhsEjb9RsoYxJIEDwRigwkOF3fMg_OPwqAhC0Rc/edit?usp=sharing
* Also update the “link” icon in the interfaces “all interpretations for this variant in the VCI” to something more obvious. 

SP ticket: https://broadinstitute.atlassian.net/browse/CSP-167

3) right indent published sections with snapshots within the "Saved Provisional and Approved" section to better reflect that 'published' is a distinct status paired with 'approved', and that publishing occurs after approval. (replaces https://github.com/ClinGen/clincoded/issues/2291)

<img width="795" alt="Screen Shot 2021-05-13 at 2 25 23 PM" src="https://user-images.githubusercontent.com/46766411/118189694-f5143100-b3f6-11eb-96f7-6dbe9b90d582.png">

SP ticket is here: https://broadinstitute.atlassian.net/browse/CSP-169. 

4) Brought up in the context of the PhyloP scores discussion, the VCI doesn't indicate that predictor values are aligned to GRCh38. Suggestion is list this at the bottom note of each tab. This was initially raised in https://github.com/ClinGen/clincoded/issues/2231

**Comment by cgpreston** [comment]
Released 1/7/2022!  As part of this SP-167 was completed (workstream rank number 6).
