### ISSUE TITLE
Interoperability in the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#54]
Display to VCI users useful information present in GCI curations.

Specifications captured here: https://docs.google.com/presentation/d/1erMmhF1MIMYHs4mpNcUh7ngXbxHIbDbGW6yshyFltlo/edit#slide=id.p

SP ticket: https://broadinstitute.atlassian.net/browse/CSP-113

Specified on 7/16/20

This ticket replaced https://github.com/ClinGen/clincoded/issues/2204

**Comment by cgpreston** [comment]
The VCI proxies have decided to archive the SP request for this ticket due to it's priority. Closing this for now.
