### ISSUE TITLE
Updates to Acknowledgements panel

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#6]
A few updates are suggested for the Acknowledgements panel:

add instructive texts
label name change

This ticket replaces https://github.com/ClinGen/clincoded/issues/2202

![Screen Shot 2020-05-11 at 13 29 31](https://user-images.githubusercontent.com/15131169/81608852-c7338100-938b-11ea-954e-6fae8cad734c.png)

1. add instructive texts

a. Under the "Acknowledge Other Contributors" button (in figure above), add instructive text so curators know they don't need to click this unless they need to acknowledge other contributors. Something like:
"You only need to *Acknowledge Other Contributors* if other groups have contributed to the supporting curation and/or approval of your Classification"

b. Under the "Classification Approvers" pulldown, add instructive text to advise curators they don't need to add in their own group as an Approver. Something along the lines of:
"If your Affiliation is the only Approver for this Classification, then do not select it here because it will be selected by default"

![Screen Shot 2020-05-11 at 13 36 41](https://user-images.githubusercontent.com/15131169/81609528-e979ce80-938c-11ea-9a2d-c6bf0f57ff2d.png)

2. label name change
Rename "Classification Approver" to "Secondary Classification Approver"
Rename "Classification Contributor" to "Secondary Classification Contributor"

**Comment by wrightmw** [comment]
@markmandell Please take a look at point 2, i.e. changing the names

**Comment by markmandell** [comment]
Same ticket https://github.com/ClinGen/gene-and-variant-curation-tools/issues/234
Merged to prod
