### ISSUE TITLE
Auto-generate interpretation evidence summary text

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#68]
On our ClinGen FDA meeting there was a request for a tool within the VCI to automatically generate a suggested text in the Evidence Summary field, based upon all the Explanation texts filled in by curators met criteria.

Need to be discussed/specified on a VCI WG call.

https://broadinstitute.atlassian.net/browse/CSP-41

**Comment by cgpreston** [comment]
This is going to be captured as a  feature for v4. Closing this ticket.
