### ISSUE TITLE
Formatting in free text fields in Evidence Summaries

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#7]
JIRA ticket: https://broadinstitute.atlassian.net/browse/CSP-163

Request from curators and experts within GCEPs for the ability to add formatting, especially paragraph breaks, but also the ability to italicize, add links, etc. in the following free text fields in the GCI:
Evidence summary
Reason for changed score
Experimental evidence explanation boxes
and preferably all other free text fields that are carried through to the PDF evidence summaries.

Also saved formatting needs to be exported when published so the website can display these fields in the desired format. Currently, some of the descriptions are quite lengthy and are increasingly cumbersome to read without paragraph breaks.

Must include:
paragraphs
italics

Desirable:
bullets
bold
URLs
underline

Export to website so can display in same format.

First look at Evidence Summaries (in both GCI and VCI).... but then:
Reason for change score
All free text fields that populate the PDF

**Comment by wrightmw** [comment]
This also applies in the VCI, especially in the Evaluation Summary field (see here, from #2088):

Text formatting, specifically line breaks, entered in the criteria evaluation section of the VCI are not maintained in the evaluation explanation in the evaluation summary section. The desired behavior is for the evaluation explanation text to mirror the criteria evaluation text

See screenshots. 

**Example 1:**
![Screen Shot 2019-12-05 at 1 01 30 PM](https://user-images.githubusercontent.com/46766411/70270375-1cbe8e80-1759-11ea-8559-5503d94c2076.png)
![Screen Shot 2019-12-05 at 1 00 59 PM](https://user-images.githubusercontent.com/46766411/70270374-1af4cb00-1759-11ea-935d-8ae8e3ec7782.png)

**Example 2:**
<img width="1117" alt="Screen Shot 2019-12-05 at 12 23 43 PM" src="https://user-images.githubusercontent.com/46766411/70270885-1e3c8680-175a-11ea-91aa-39b47f6bf9fa.png">
<img width="1155" alt="Screen Shot 2019-12-05 at 12 22 37 PM" src="https://user-images.githubusercontent.com/46766411/70270804-0107b800-175a-11ea-88a3-a8c2894382b2.png">

**Comment by cgpreston** [comment]
@wrightmw , can we close this?
