### ISSUE TITLE
HGNC gene symbols in italics in Evidence Summary table

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#8]
HGNC gene symbols should be in italics in Evidence Summaries.

This ticket replaces https://github.com/ClinGen/clincoded/issues/2232

**Comment by markmandell** [comment]
@wrightmw good starting ticket?

**Comment by liammulh** [comment]
The text "Evidence Summary" shows up a lot in the code, so it's not clear to me what code I need to modify. Could either @markmandell or @wrightmw provide some instructions on how to navigate to this table in the interface? Thanks!

**Comment by wrightmw** [comment]
@courtneythaxton you initially raised this issue. Can you please clarify which location you are referring to? Is this fixed by the Evidence Summary edit tool?

**Comment by courtneythaxton** [comment]
I believe it was satisfied when you all added the MArkdown in the Evidence summary allowing italics and bolding :)

**Comment by liammulh** [comment]
I double-checked, and it looks like markdown is working reasonably well in the evidence summary text edit tool:

![md](https://github.com/ClinGen/gene-and-variant-curation-tools/assets/60749003/5044d2f3-6463-45b8-9306-a4ceab818cb5)

Okay to close, @wrightmw?

**Comment by wrightmw** [comment]
@liammulh Yeah, thank for you checking. You can close this ticket out.
