### ISSUE TITLE
Add Typeahead Searching to Non-human Model Organism Pulldowns

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#9]
Users add non-human model organisms via a pulldown in two locations in the GCI. 

1.  Experimental Data>Model Systems

e.g.
![Screen Shot 2022-08-08 at 10 04 59 AM](https://user-images.githubusercontent.com/15131169/183473753-85c5dd17-6094-4e89-9baa-f86d12d50c3a.png)

2. Experimental Data>Rescue

We need to change these two pulldowns so they are instead structured same way as the "Classification Approvers"

![Screen Shot 2022-08-08 at 10 06 16 AM](https://user-images.githubusercontent.com/15131169/183474287-8fdf06a7-973d-49e0-a000-195fb90b0717.png)

That is, we need them to be able to do typeaheads for the pulldowns. So the organism they are looking for in the list will appear when they start typing....

**Comment by wrightmw** [comment]
@markmandell I've updated this ticket, per our conversation just now.

**Comment by markmandell** [comment]
merged to prod
