### ISSUE TITLE
GCI data output request

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#92]
Data output request from GCI, to include:
Gene, disease, MOI, GCEP affiliation, final classification, final classification date, SOP version number, genetic points, experimental points, total points, number of probands

**Comment by wrightmw** [comment]
Note. This request is for all GCEP affiliations, and Approved records only.

**Comment by ErinRiggs** [comment]
Thanks for creating this ticket, Matt.  Do you have any rough estimate of timeline?  I'm just trying to decide if it is easiest/more time efficient to do this through the GCI, or to wait until all the information is validated in GeneGraph and get it from there.  Do you have any recommendations?

**Comment by wrightmw** [comment]
@ErinRiggs  Rao is out over the next few days, and so I can't give you a proper estimate until next week. However, I would guesstimate that this should be able to be done within the next few weeks.

**Comment by ErinRiggs** [comment]
Ok!  That sounds reasonable, but let me know if that changes once you speak with Rao!

**Comment by cgpreston** [comment]
Also please add dates of latest clinical publication.  @courtneythaxton please add details.

**Comment by wrightmw** [comment]
Done.
